[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: {data_path}/comms/klippy.sock
max_upload_size: 100

[authorization]
trusted_clients:
    10.0.0.0/8
    172.16.0.0/12
    192.168.0.0/16
    127.0.0.0/8
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.mainsail.xyz

[octoprint_compat]

[history]

[file_manager]
enable_object_processing: True
enable_config_write_access: True

[machine]
shutdown_action: halt
sudo_password: <your-sudo-password>

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: /home/pi/mainsail

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen

[timelapse]

[update_manager timelapse]
type: git_repo
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
